Repository RPalaciosDev/csumb-programming-team-archive, pull requests merged in 2025-07, with the labels that each got.

#1 Initial Setup of CSUMB Programming Team Archive
  README.md
  solutions/leetcode/703-kth-largest-element-in-a-stream/README.md
  templates/cpp_template.cpp
  templates/java_template.java
  templates/python_template.py
Labels: good first issue

#3 Remove space following octothorp
  templates/cpp_template.cpp
Labels: bug

#9 Reorganize Solution Structure and Add Heap-Based Solutions
  solutions/leetcode/1046-last-stone-weight/C++/2025-07-23_RuizMireles.cpp
  solutions/leetcode/1046-last-stone-weight/Python/2025-07-21_Palacios.py
  solutions/leetcode/621-task-scheduler/README.md
  solutions/leetcode/703-kth-largest-element-in-a-stream/Python/2025-07-21_Palacios.py
  solutions/leetcode/973-k-closest-points-to-origin/C++/2025-07-23_RuizMireles.cpp
  solutions/leetcode/973-k-closest-points-to-origin/README.md
Labels: documentation, enhancement
